print("Kristuf Jeruz J. Lamonte")
print("Pangi, Gasan, Marinduque")
print("August 12, 2002")
print("")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("BSIT - 2C")
print("")
print("Playing online games.")
print("Playing basketball.")
print("Drawing and coloring.")
print("Watching movies.")
print("Cooking")