print("Kristuf Jeruz J. Lamonte")
print("Pangi, Gasan, Marinduque")
print("August 12, 2002")
print("")
print("Marinduque State College")
print("Bachelor of Science in Information Technology")
print("BSIT - 2C")